### ISSUE TITLE
How to use??

### ISSUE THREAD

**Issue by as1ndu** [mawie81/whatsdesktop#1] opened 2015-12-17 12:00 UTC
**How to use??**
It runs very well but all i see is a blank screen. How to i get started(add contacts, chat etc)?
![untitled](https://cloud.githubusercontent.com/assets/4271996/11869191/85b42b68-a4b5-11e5-8687-0e3f9c0b8cb8.png)
## 

WhatsDesktop 1.2.0
win32 ia32 10.0.10240

**Comment by miguelpalazzo** [comment] 2015-12-17 13:57
Something similar happened to me on Mac OS X. I left it open for about 20 minutes, yet the white screen remained and none of its top bar actions seemed to work for me. Re-opening the app didn't help either.

WhatsDesktop 1.2.0

**Comment by mawie81** [comment] 2015-12-17 14:48
Hm thats strange. I´ve never seen this before.
Does https://web.whatsapp.com/ work for you?

**Comment by miguelpalazzo** [comment] 2015-12-18 14:52
The page works for me @mawie81, rather limited since I don't have a supported phone to actually activate the service. Didn't think that was a requirement to use the app, not sure if it's specified anywhere on documentation or not, but I'm sorry for my concern here. Thanks!

**Comment by mawie81** [comment] 2015-12-19 10:06
I just added a note that a WhatsApp Web compatible device is needed.
As for the white screen: I still can not reproduce this.

Are you using the binary release from the releases page or did you build it yourself?
If the former: Could try to clone this repo, run `npm install &&  npm start` and have look if any error appear in the console?

**Comment by mawie81** [comment] 2016-02-23 18:17
Closing this because I still can´t reproduce and no one else seems to run into this.

**Closed as completed by mawie81** 2016-02-23 18:17 UTC
